#!/usr/bin/env bash
#

# Handle SIGTERM signal by printing a message instead of exiting
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop with a 2-second pause
while true
do
    echo "To infinity and beyond"
    sleep 2
done
