#!/usr/bin/env bash
# This script displays numbers from 1 to 100 and displays FizzBuzz, Fizz, or Buzz for multiples of 15, 3, or 5 respectively
for ((i=1; i<=100; i++))
do
    if [ $((i % 15)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo $i
    fi
done
